name: 'Terraform CI/CD'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  TF_ROOT: "./"
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  setup:
    name: Setup Terraform
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout Code  # Checkout only once
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Restore Terraform Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: .terraform/
          key: terraform-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            terraform-${{ github.ref }}-

      - name: Initialize Terraform
        run: terraform init

      - name: Save Workspace as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .  # Save everything for reuse

  fmt:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Terraform Format Check
        run: terraform fmt -check

  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    needs: [setup, fmt]
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Terraform Validate
        run: terraform validate

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Terraform Plan
        run: terraform plan -var-file=secrets.tfvars -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

  apply:
    name: Terraform Apply (Manual)
    runs-on: ubuntu-latest
    needs: plan
    environment: production
    steps:
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve tfplan
